### ISSUE TITLE
Dependency on vcruntime140.dll

### ISSUE THREAD

**Issue by PhilPJL** [HDFGroup/HDF.PInvoke#183]
After installing our application on a fresh install of Windows 10 it appears there's a dependency on vcruntime140.dll when using HDF.PInvoke.1.10 (1.10.612).  This can be verified by using a dependency checker such as this [https://github.com/lucasg/Dependencies](https://github.com/lucasg/Dependencies).
![image](https://user-images.githubusercontent.com/271656/175026389-e256aa29-2eeb-464c-9811-0017e792a984.png)
This is showing the dll installed in system32 on my dev box.  The dll isn't there by default.

This is easily remedied but maybe vcruntime140.dll should be included in the package?

**Comment by Apollo3zehn** [comment]
https://docs.microsoft.com/en-us/cpp/windows/redistributing-visual-cpp-files?view=msvc-170#install-the-redistributable-packages also mentions the advantage of installing the redistributable package: 

_The Visual C++ Redistributable Packages install and register all Visual C++ libraries. If you use one, run it as a prerequisite on the target system before you install your application. We recommend that you use these packages for your deployments because they enable **automatic updating** of the Visual C++ libraries._

**Comment by PhilPJL** [comment]
ok thanks for the info.
