### ISSUE TITLE
How do represent H5F_retry_info_t?

### ISSUE THREAD

**Issue by gheber** [HDFGroup/HDF.PInvoke#68]
```
/* The number of metadata entries with checksum */
#define NUM_METADATA_READ_RETRIES         21        

typedef struct H5F_retry_info_t {
    unsigned nbins;
    uint32_t *retries[H5F_NUM_METADATA_READ_RETRY_TYPES];
} H5F_retry_info_t;
```

I can't have pointers in fixed arrays `:-(`.

**Comment by hokb** [comment]
I think `IntPtr[]` will do? 
Being concerned about this statement in the docu for [H5Fget_metadata_read_retry_info](https://www.hdfgroup.org/HDF5/docNewFeatures/FineTuneMDC/H5Fget_metadata_read_retry_info.htm):

> After a call to this routine, users should free each retries[i] that is non-NULL, otherwise resource leak will occur.

Is there a free function exposed from the HDF5 API? Otherwise, how can we make sure to use the same C++ runtime version as were used inside HDF5 for allocating this storage? Or am I missing something?

**Comment by hokb** [comment]
Doesn't this issue apply the same for users of the C API?

**Comment by gheber** [comment]
> Is there a free() function exposed from the HDF5 API?

Yes, it's called `H5.free_memory`.

**Comment by gheber** [comment]
> I think `IntPtr[]` will do? 

No, because the storage layout would be different from `H5F_retry_info_t`. It would give us an unsigned integer followed by a pointer. We need an unsigned integer followed by 32 pointers! Since we can't have a fixed-size array of pointers, we'll just have to hard-code one.
```
public struct retry_info_t
{
  public uint nbins;
  public IntPtr retries0;
  public IntPtr retries1;
  public IntPtr retries2;
  ...
  public IntPtr retries20;
}
```
Ugly, but effective. Fortunately, `H5F.NUM_METADATA_READ_RETRY_TYPES` is not going to change frequently.
