### ISSUE TITLE
nuget package postbuild event not working

### ISSUE THREAD

**Issue by hokb** [HDFGroup/HDF.PInvoke#74]
When adding the nuget package to a solution the following (example) postbuild event gets added to the project referencing HDF.PInvoke automatically: 

```
if not exist "$(TargetDir)bin32" md "$(TargetDir)bin32"
xcopy /s /y "$(SolutionDir)test\HDF5_UnitTests\packages\HDF.PInvoke.1.8.17.2\lib\native\bin32\*.*" "$(TargetDir)bin32"
if not exist "$(TargetDir)bin64" md "$(TargetDir)bin64"
xcopy /s /y "$(SolutionDir)test\HDF5_UnitTests\packages\HDF.PInvoke.1.8.17.2\lib\native\bin64\*.*" "$(TargetDir)bin64"</PostBuildEvent>
```

The source path in the xcopy command is wrong. I am currently investigating why.

**Comment by hokb** [comment]
Here is what is produced at build time: 

    The command "
    if not exist "D:\dev\ILNumerics-dev\Projects\ILNumerics.IO.HDF5\src\bin\Debug\bin32" md "D:\dev\ILNumerics-dev\Projects\ILNumerics.IO.HDF5\src\bin\Debug\bin32"
    xcopy /s /y "D:\dev\ILNumerics-dev\Projects\ILNumerics.IO.HDF5\test\HDF5_UnitTests\test\HDF5_UnitTests\packages\HDF.PInvoke.1.8.17.2\lib\native\bin32\*.*" "D:\dev\ILNumerics-dev\Projects\ILNumerics.IO.HDF5\src\bin\Debug\bin32"
    if not exist "D:\dev\ILNumerics-dev\Projects\ILNumerics.IO.HDF5\src\bin\Debug\bin64" md "D:\dev\ILNumerics-dev\Projects\ILNumerics.IO.HDF5\src\bin\Debug\bin64"
    xcopy /s /y "D:\dev\ILNumerics-dev\Projects\ILNumerics.IO.HDF5\test\HDF5_UnitTests\test\HDF5_UnitTests\packages\HDF.PInvoke.1.8.17.2\lib\native\bin64\*.*" "D:\dev\ILNumerics-dev\Projects\ILNumerics.IO.HDF5\src\bin\Debug\bin64"" exited with code 4.

**Comment by hokb** [comment]
Cannot find the error right now. I fixed it locally by fixing the post build event. Somehow the relative sub path SolutionDir -> ProjectDir showed up twice. 

It might has to do with the ` char being added to the beginning of `$path` in line 2 in [GetHDFPostBuildCmd.ps1](https://github.com/HDFGroup/HDF.PInvoke/blob/master/NuGet/tools/GetHDFPostBuildCmd.ps1). But this is only a guess.

**Comment by hokb** [comment]
Unfortunately, this issue still exists. Once the project referencing the nuget package is used in multiple solutions, the position of the downloaded binary folders differ. This causes the post build event to fail.

 I don't know a better way to reference the `packages` folder relative to the project. But the current way to use `$(SolutionDir)` seems not robust enough.

**Comment by hokb** [comment]
Well, a viable solution of course would be to carefully store all solutions referencing the project referencing HDF.PInvoke _in the same folder_. I'll leave this issue open nevertheless. Maybe someone comes up with a better suggestion?

**Comment by JanWosnitza** [comment]
First of all, NuGet tries to get rid of the PowerShell-Script support since it has a major drawback:
It only works within VS using the VS-NuGet Plugin, meaning the NuGet command-line isn't able to install the package correctly (additionally [Paket](https://fsprojects.github.io/Paket/), a popular NuGet-Client alternative, has the same problem).

Also, @hokb, you told me (yesterday), that the script doesn't work as expected all the time.

#### My suggestion
Replace the PS-scripts with an [MSBuild .targets file](https://msdn.microsoft.com/en-us/library/ms164312.aspx) which sits in the [NuGet package's build folder](https://docs.nuget.org/ndocs/create-packages/creating-a-package#from-a-convention-based-working-directory).

The `HDF.PInvoke.targets` file should look similar to this:

	<?xml version="1.0" encoding="utf-8"?>
	<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	  <ItemGroup>
		<None Include="$(MSBuildThisFileDirectory)$(Platform)/hdf5.dll">
		  <Link>hdf5.dll</Link>
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Include="$(MSBuildThisFileDirectory)$(Platform)/hdf5.pdb">
		  <Link>hdf5.pdb</Link>
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		
	  </ItemGroup>
	</Project>

and the NuGet package's build folder will look like:

- build
  - x86
    - hdf5.dll
    - hdf5.pdb
  - x64
    - hdf5.dll
    - hdf5.pdb
  - HDF.PInvoke.targets

#### Advantages

- The package is installation works within VS and on command-line tools (NuGet + Paket)
- The native libraries don't show up in the solution explorer of the project using the package
- The native libraries are copied only into the bin folders and not the project folders
- NuGet takes care of the ´.targets´ being added to the project

#### "Disadvantages"

- The overall approach works, but I havn't tested the `$(Platform)` part yet.

**Comment by JanWosnitza** [comment]
Or when all native library platform versions (x86, x64, maybe even Linux & MacOS) should be copied to the project's output folder, such that the platform independent .Net binary runs on all plattforms: change the ´HDF.PInvoke.targets´ to something like (untested):

	<?xml version="1.0" encoding="utf-8"?>
	<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	  <ItemGroup>
		<None Include="$(MSBuildThisFileDirectory)x86/hdf5.dll">
		  <Link>platform/x86/hdf5.dll</Link>
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Include="$(MSBuildThisFileDirectory)x86/hdf5.pdb">
		  <Link>platform/x86/hdf5.pdb</Link>
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		
		<None Include="$(MSBuildThisFileDirectory)x64/hdf5.dll">
		  <Link>platform/x64/hdf5.dll</Link>
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Include="$(MSBuildThisFileDirectory)x64/hdf5.pdb">
		  <Link>platform/x64/hdf5.pdb</Link>
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		
	  </ItemGroup>
	</Project>

The appropriate platform folder has to be decided on runtime ([SetDllDirectory](https://msdn.microsoft.com/en-us/library/windows/desktop/ms686203(v=vs.85).aspx) on Windows).

**Comment by JanWosnitza** [comment]
Hopefully fixed with the `.targets` file.
